# Environment Configuration for 

environment:
  name: 
  created_by: seyoawe
  created_at: "now"

settings:
  region: us-west-2
  instance_type: t3.medium
  replicas: 2

features:
  - autoscaling: True
  - logging: enabled
  - monitoring: basic

metadata:
  workflow_id: 
  git_branch: feature-